services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3:rw
      - static_files_volume:/usr/src/app/staticfiles:rw
      - media_volume:/usr/src/app/media:rw
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
  redis:
    image: redis:7.2
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  proxy:
    image: nginx:1.25
    ports:
      - "2000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files_volume:/usr/share/nginx/html/static/:ro
      - media_volume:/usr/share/nginx/html/media/:ro
    depends_on:
      web:
        condition: service_healthy

volumes:
  static_files_volume:
  media_volume:
