services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3:rw
      - static_files_volume:/usr/src/app/staticfiles:rw
      - media_volume:/usr/src/app/media:rw
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx:1.25
    ports:
      - "127.0.0.1:2000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files_volume:/usr/share/nginx/html/static/:ro
      - media_volume:/usr/share/nginx/html/media/:ro
    depends_on:
      web:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl http://127.0.0.1:9200
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  kibana:
    image: kibana:8.15.1
    env_file:
      - .env
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=pass
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=basic
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  static_files_volume:
  media_volume:
  esdata:
