# Generated by Django 4.2.5 on 2023-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(default='Shahid Beheshti University', max_length=255),
            preserve_default=False,
        ),
    ]
