# Generated by Django 4.2.5 on 2023-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_experience_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='company_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='company_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
