# Generated by Django 4.2.10 on 2024-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_certificate_company_alter_education_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(default='https://moeinarabi.ir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(max_length=255),
        ),
    ]
