# Generated by Django 4.2.6 on 2023-11-09 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('page', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[\\w.,:()-=+!/?|\'\\"{}: ]*$')])),
                ('tags', models.ManyToManyField(to='engineer.tag')),
            ],
        ),
    ]
