# Generated by Django 4.2.7 on 2024-01-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_footprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetcodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leetcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('problem_beauty', models.IntegerField(choices=[(1, 'Bad'), (2, 'Review If Have Time'), (3, 'Good For Review'), (4, 'Very Insightful Idea')])),
                ('url', models.URLField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='engineer.leetcodetag')),
            ],
        ),
    ]
