# Generated by Django 4.2.7 on 2024-01-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_leetcodetag_leetcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeetcodeTag',
            new_name='LeetcodeTopic',
        ),
    ]
