# Generated by Django 4.2.15 on 2024-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0007_vocabulary_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='translation',
            field=models.TextField(blank=True),
        ),
    ]
