# Generated by Django 4.2.4 on 2023-09-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('D', 'Downloading'), ('C', 'Complete'), ('F', 'Fail')], default='D', max_length=255)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('saved_path', models.CharField(max_length=255, null=True)),
                ('download_url', models.CharField(max_length=255, null=True)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.playlistmodel')),
            ],
        ),
    ]
