# Generated by Django 4.2.4 on 2023-09-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='progress',
        ),
    ]
