# Generated by Django 4.2.4 on 2023-09-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_videomodel_progress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistModel',
            new_name='Playlist',
        ),
        migrations.RenameModel(
            old_name='VideoModel',
            new_name='Video',
        ),
    ]
