name: CI-Docker

on:
  workflow_run:
    workflows:
      - CI-Django
    types:
      - completed
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
    - name: Push to the registry
      run: docker push
