name: CI-Docker

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
    - name: Push to the registry
      run: docker push
