name: CD-Liara

on:
  workflow_call:

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
      APP_NAME: toolbox

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install-liara
        run: npm i -g @liara/cli@5
      - name: update-liara
        run: liara deploy --app="$APP_NAME" --api-token="$LIARA_TOKEN" --port=8000 --no-app-logs
