name: Release

on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/django.yml

  deploy_liara:
    needs:
      - test
    uses: ./.github/workflows/liara.yml

  build_image:
    needs:
      - test
    uses: ./.github/workflows/docker.yml
